# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ME4L.ui'
#
# Created: Tue Feb 28 20:44:31 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(796, 838)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Mobot Explorer 4 Linux", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/navigate/Icons/crystal-project-actions-PNG/PNG/run-256.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame_2 = QtGui.QFrame(self.tab)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout = QtGui.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(42, 16777215))
        self.label_2.setBaseSize(QtCore.QSize(0, 0))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.port = QtGui.QComboBox(self.frame_2)
        self.port.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Wybierz port szeregowy do którego podłączony jest nadajnik radiowy robota", None, QtGui.QApplication.UnicodeUTF8))
        self.port.setObjectName(_fromUtf8("port"))
        self.horizontalLayout_3.addWidget(self.port)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.connect = QtGui.QCheckBox(self.frame_2)
        self.connect.setMinimumSize(QtCore.QSize(0, 0))
        self.connect.setMaximumSize(QtCore.QSize(81, 16777215))
        self.connect.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Zaznacz, jeżeli chcesz się połączyć z robotem na wybranym porcie szeregowym.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Uwaga!</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Jeżeli w ciągu dwóch sekund nie nastąpi komunikacja z robotem, program automatycznie się rozłączy.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.connect.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.connect.setAutoFillBackground(False)
        self.connect.setText(QtGui.QApplication.translate("MainWindow", "Połącz", None, QtGui.QApplication.UnicodeUTF8))
        self.connect.setObjectName(_fromUtf8("connect"))
        self.horizontalLayout_2.addWidget(self.connect)
        spacerItem = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.status = QtGui.QLabel(self.frame_2)
        self.status.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Pole to informuje o aktualnym stanie połączenia z robotem.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Kiedy program utrzymuje z robotem komunikację, pole to wyświetla status: &quot;<span style=\" font-weight:600;\">Połączony</span>&quot;.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Jeżeli brak połączenia z robotem, pole to wyświetla komunikat: &quot;<span style=\" font-weight:600;\">Brak komunikacji</span>&quot;.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setAutoFillBackground(False)
        self.status.setStyleSheet(_fromUtf8("background: rgb(200, 160, 160);"))
        self.status.setFrameShape(QtGui.QFrame.StyledPanel)
        self.status.setFrameShadow(QtGui.QFrame.Sunken)
        self.status.setLineWidth(1)
        self.status.setText(QtGui.QApplication.translate("MainWindow", "Niepołączony", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setObjectName(_fromUtf8("status"))
        self.horizontalLayout_2.addWidget(self.status)
        self.line = QtGui.QFrame(self.frame_2)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_2.addWidget(self.line)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Sonar 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Sonar 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Sonar 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.sonar1 = QtGui.QProgressBar(self.frame)
        self.sonar1.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Pokazuje odległość robota od przeszkody w pierwszym sonarze.\n"
"\n"
"Im pasek bliżej prawej krawędzi tym bliżej sonaru.", None, QtGui.QApplication.UnicodeUTF8))
        self.sonar1.setMaximum(255)
        self.sonar1.setProperty("value", 0)
        self.sonar1.setFormat(QtGui.QApplication.translate("MainWindow", "%p", None, QtGui.QApplication.UnicodeUTF8))
        self.sonar1.setObjectName(_fromUtf8("sonar1"))
        self.horizontalLayout_4.addWidget(self.sonar1)
        self.sonar2 = QtGui.QProgressBar(self.frame)
        self.sonar2.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Pokazuje odległość robota od przeszkody w drugim sonarze.\n"
"\n"
"Im pasek bliżej prawej krawędzi tym bliżej sonaru.", None, QtGui.QApplication.UnicodeUTF8))
        self.sonar2.setMaximum(255)
        self.sonar2.setProperty("value", 0)
        self.sonar2.setFormat(QtGui.QApplication.translate("MainWindow", "%p", None, QtGui.QApplication.UnicodeUTF8))
        self.sonar2.setObjectName(_fromUtf8("sonar2"))
        self.horizontalLayout_4.addWidget(self.sonar2)
        self.sonar3 = QtGui.QProgressBar(self.frame)
        self.sonar3.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Pokazuje odległość robota od przeszkody w trzecim sonarze.\n"
"\n"
"Im pasek bliżej prawej krawędzi tym bliżej sonaru.", None, QtGui.QApplication.UnicodeUTF8))
        self.sonar3.setMaximum(255)
        self.sonar3.setProperty("value", 0)
        self.sonar3.setFormat(QtGui.QApplication.translate("MainWindow", "%p", None, QtGui.QApplication.UnicodeUTF8))
        self.sonar3.setObjectName(_fromUtf8("sonar3"))
        self.horizontalLayout_4.addWidget(self.sonar3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 2, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Sterowanie", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.moveLeft = QtGui.QPushButton(self.groupBox)
        self.moveLeft.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Uruchamia robota do skrętu w lewo.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Skrótem na klawiaturze do tego przycisku jest <span style=\" font-weight:600;\">strzałka w lewo</span>.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.moveLeft.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/crystal-project-actions-PNG/PNG/2leftarrow-256.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveLeft.setIcon(icon1)
        self.moveLeft.setIconSize(QtCore.QSize(128, 128))
        self.moveLeft.setShortcut(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.moveLeft.setCheckable(False)
        self.moveLeft.setAutoRepeat(True)
        self.moveLeft.setAutoExclusive(False)
        self.moveLeft.setAutoRepeatDelay(300)
        self.moveLeft.setAutoRepeatInterval(100)
        self.moveLeft.setObjectName(_fromUtf8("moveLeft"))
        self.gridLayout_3.addWidget(self.moveLeft, 1, 4, 1, 1)
        self.moveRight = QtGui.QPushButton(self.groupBox)
        self.moveRight.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Uruchamia robota do skrętu w prawo.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Skrótem na klawiaturze do tego przycisku jest <span style=\" font-weight:600;\">strzałka w prawo</span>.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.moveRight.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/crystal-project-actions-PNG/PNG/2rightarrow-256.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveRight.setIcon(icon2)
        self.moveRight.setIconSize(QtCore.QSize(128, 128))
        self.moveRight.setShortcut(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.moveRight.setAutoRepeat(True)
        self.moveRight.setObjectName(_fromUtf8("moveRight"))
        self.gridLayout_3.addWidget(self.moveRight, 0, 4, 1, 1)
        self.moveUp = QtGui.QPushButton(self.groupBox)
        self.moveUp.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Uruchamia robota do jazdy do przodu.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Skrótem na klawiaturze do tego przycisku jest <span style=\" font-weight:600;\">strzałka w górę</span>.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.moveUp.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/crystal-project-actions-PNG/PNG/2uparrow-256.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveUp.setIcon(icon3)
        self.moveUp.setIconSize(QtCore.QSize(128, 128))
        self.moveUp.setShortcut(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.moveUp.setAutoRepeat(True)
        self.moveUp.setObjectName(_fromUtf8("moveUp"))
        self.gridLayout_3.addWidget(self.moveUp, 0, 3, 1, 1)
        self.moveDown = QtGui.QPushButton(self.groupBox)
        self.moveDown.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Uruchamia robota do jazy do tyłu.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Skrótem na klawiaturze do tego przycisku jest <span style=\" font-weight:600;\">strzałka w dół</span>.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.moveDown.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/crystal-project-actions-PNG/PNG/2downarrow-256.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveDown.setIcon(icon4)
        self.moveDown.setIconSize(QtCore.QSize(128, 128))
        self.moveDown.setShortcut(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.moveDown.setAutoRepeat(True)
        self.moveDown.setObjectName(_fromUtf8("moveDown"))
        self.gridLayout_3.addWidget(self.moveDown, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.stop = QtGui.QPushButton(self.groupBox)
        self.stop.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Zatrzymuje robota w miejscu.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Skrótem na klawiaturze do tego przycisku jest <span style=\" font-weight:600;\">spacja</span>.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.stop.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("Icons/crystal-project-actions-PNG/PNG/stop-256.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon5)
        self.stop.setIconSize(QtCore.QSize(128, 128))
        self.stop.setShortcut(QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.stop.setObjectName(_fromUtf8("stop"))
        self.verticalLayout_2.addWidget(self.stop)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 2, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 2, 6, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 3, 2, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Szybkość", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.speed = QtGui.QDial(self.frame)
        self.speed.setToolTip(QtGui.QApplication.translate("MainWindow", "Szybkość robota", None, QtGui.QApplication.UnicodeUTF8))
        self.speed.setMinimum(1)
        self.speed.setMaximum(100)
        self.speed.setSliderPosition(50)
        self.speed.setOrientation(QtCore.Qt.Horizontal)
        self.speed.setInvertedAppearance(False)
        self.speed.setInvertedControls(False)
        self.speed.setWrapping(False)
        self.speed.setNotchTarget(18.7)
        self.speed.setNotchesVisible(False)
        self.speed.setObjectName(_fromUtf8("speed"))
        self.verticalLayout_4.addWidget(self.speed)
        spacerItem5 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.labelSpeedPercent = QtGui.QLabel(self.frame)
        self.labelSpeedPercent.setText(_fromUtf8(""))
        self.labelSpeedPercent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSpeedPercent.setObjectName(_fromUtf8("labelSpeedPercent"))
        self.gridLayout_8.addWidget(self.labelSpeedPercent, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_8)
        self.gridLayout_5.addLayout(self.verticalLayout_4, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.gridLayout_6.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.radioChannel = QtGui.QComboBox(self.tab_2)
        self.radioChannel.setObjectName(_fromUtf8("radioChannel"))
        self.radioChannel.addItem(_fromUtf8(""))
        self.radioChannel.setItemText(0, QtGui.QApplication.translate("MainWindow", "Kanał 0 - 868,0 Mhz", None, QtGui.QApplication.UnicodeUTF8))
        self.radioChannel.addItem(_fromUtf8(""))
        self.radioChannel.setItemText(1, QtGui.QApplication.translate("MainWindow", "Kanał 1 - 868,2 Mhz", None, QtGui.QApplication.UnicodeUTF8))
        self.radioChannel.addItem(_fromUtf8(""))
        self.radioChannel.setItemText(2, QtGui.QApplication.translate("MainWindow", "Kanał 2 - 868,4 Mhz", None, QtGui.QApplication.UnicodeUTF8))
        self.radioChannel.addItem(_fromUtf8(""))
        self.radioChannel.setItemText(3, QtGui.QApplication.translate("MainWindow", "Kanał 3 - 868,6 Mhz", None, QtGui.QApplication.UnicodeUTF8))
        self.radioChannel.addItem(_fromUtf8(""))
        self.radioChannel.setItemText(4, QtGui.QApplication.translate("MainWindow", "Kanał 4 - 868,8 Mhz", None, QtGui.QApplication.UnicodeUTF8))
        self.radioChannel.addItem(_fromUtf8(""))
        self.radioChannel.setItemText(5, QtGui.QApplication.translate("MainWindow", "Kanał 5 - 868,10 Mhz", None, QtGui.QApplication.UnicodeUTF8))
        self.radioChannel.addItem(_fromUtf8(""))
        self.radioChannel.setItemText(6, QtGui.QApplication.translate("MainWindow", "Kanał 6 - 868,12 Mhz", None, QtGui.QApplication.UnicodeUTF8))
        self.radioChannel.addItem(_fromUtf8(""))
        self.radioChannel.setItemText(7, QtGui.QApplication.translate("MainWindow", "Kanał 7 - 868,14 Mhz", None, QtGui.QApplication.UnicodeUTF8))
        self.radioChannel.addItem(_fromUtf8(""))
        self.radioChannel.setItemText(8, QtGui.QApplication.translate("MainWindow", "Kanał 8 - 868,16 Mhz", None, QtGui.QApplication.UnicodeUTF8))
        self.radioChannel.addItem(_fromUtf8(""))
        self.radioChannel.setItemText(9, QtGui.QApplication.translate("MainWindow", "Kanał 9 - 868,18 Mhz", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_8.addWidget(self.radioChannel)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Moc nadajnika", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.power = QtGui.QDial(self.tab_2)
        self.power.setMaximum(7)
        self.power.setPageStep(1)
        self.power.setProperty("value", 7)
        self.power.setWrapping(False)
        self.power.setNotchesVisible(True)
        self.power.setObjectName(_fromUtf8("power"))
        self.verticalLayout.addWidget(self.power)
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Szybkość komunikacji", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_5.addWidget(self.label_7)
        self.uartspeed = QtGui.QDial(self.tab_2)
        self.uartspeed.setMinimum(1)
        self.uartspeed.setMaximum(56)
        self.uartspeed.setPageStep(1)
        self.uartspeed.setProperty("value", 40)
        self.uartspeed.setWrapping(False)
        self.uartspeed.setNotchesVisible(True)
        self.uartspeed.setObjectName(_fromUtf8("uartspeed"))
        self.verticalLayout_5.addWidget(self.uartspeed)
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_5.addWidget(self.label_10)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Czułość odbiornika", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_6.addWidget(self.label_8)
        self.sensitivity = QtGui.QDial(self.tab_2)
        self.sensitivity.setMinimum(0)
        self.sensitivity.setMaximum(3)
        self.sensitivity.setPageStep(1)
        self.sensitivity.setProperty("value", 3)
        self.sensitivity.setWrapping(False)
        self.sensitivity.setNotchesVisible(True)
        self.sensitivity.setObjectName(_fromUtf8("sensitivity"))
        self.verticalLayout_6.addWidget(self.sensitivity)
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_6.addWidget(self.label_11)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Wielkość bufora", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_7.addWidget(self.label_13)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.bufferSize = QtGui.QSlider(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bufferSize.sizePolicy().hasHeightForWidth())
        self.bufferSize.setSizePolicy(sizePolicy)
        self.bufferSize.setMinimumSize(QtCore.QSize(0, 0))
        self.bufferSize.setMaximumSize(QtCore.QSize(647, 16777215))
        self.bufferSize.setBaseSize(QtCore.QSize(0, 0))
        self.bufferSize.setMaximum(128)
        self.bufferSize.setSingleStep(4)
        self.bufferSize.setProperty("value", 8)
        self.bufferSize.setOrientation(QtCore.Qt.Horizontal)
        self.bufferSize.setInvertedAppearance(False)
        self.bufferSize.setInvertedControls(False)
        self.bufferSize.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.bufferSize.setObjectName(_fromUtf8("bufferSize"))
        self.horizontalLayout_5.addWidget(self.bufferSize)
        spacerItem6 = QtGui.QSpacerItem(29, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.label_12 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        self.label_12.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_5.addWidget(self.label_12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.gridLayout_10.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 478, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem7, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.radioStatus = QtGui.QLabel(self.tab_2)
        self.radioStatus.setFrameShape(QtGui.QFrame.Panel)
        self.radioStatus.setFrameShadow(QtGui.QFrame.Sunken)
        self.radioStatus.setText(_fromUtf8(""))
        self.radioStatus.setObjectName(_fromUtf8("radioStatus"))
        self.horizontalLayout_7.addWidget(self.radioStatus)
        self.gridLayout_10.addLayout(self.horizontalLayout_7, 3, 0, 1, 1)
        self.warn = QtGui.QLabel(self.tab_2)
        self.warn.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#800000;\">Uwaga!</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#800000;\">Ustawienia na tej zakładce mogą powodować brak komunikacji z robotem!</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.warn.setObjectName(_fromUtf8("warn"))
        self.gridLayout_10.addWidget(self.warn, 2, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.power, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_9.setNum)
        QtCore.QObject.connect(self.uartspeed, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_10.setNum)
        QtCore.QObject.connect(self.sensitivity, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_11.setNum)
        QtCore.QObject.connect(self.bufferSize, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_12.setNum)
        QtCore.QObject.connect(self.speed, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.labelSpeedPercent.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Robot", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Radio", None, QtGui.QApplication.UnicodeUTF8))

import mainicons_rc
